<div class="wrapper screen">
    <div class="clear wrapper-404">
        <div class="left" style="text-align: center;">
            <img src="http://img09.hunchelaila.com/resource/2016/06/06/18/resource41b4ce2bdb7131a89d069fc3b445c174.png" style="padding-top: 100px;">
        </div>
        <div class="right right-tips">
            <p class="text2">
                <?php
                if(!empty($exception)){
                    echo "Error Msg:"  . $exception->getMessage();
                }
                ?>
            </p>
        </div>
    </div>
</div>