
<?php var_dump($user);?>

<table border=20 width=500 align=center>
 <tr align=center>
  <td>Name</td>
  <td>QF(QINFramework)</td>
 </tr>
 
  <tr align=center>
  <td>Version</td>
  <td>QF2.0</td>
 </tr>
 
  <tr align=center>
  <td>Author</td>
  <td>lirong.zhang</td>
 </tr>
 
  <tr align=center>
  <td>Email</td>
  <td>i@zhanglirong.cn</td>
 </tr>
 
  <tr align=center>
  <td>Wechart</td>
  <td>wutong_q</td>
 </tr>
 
  <tr align=center>
  <td>Blog</td>
  <td><a href='http://www.zhanglirong.cn?from=qf'>http://www.zhanglirong.cn</a></td>
 </tr>
 
  <tr align=center>
  <td>QQ</td>
  <td>1052099864</td>
 </tr>
</table>

